<?php


namespace OnzaMe\Helpers;


class UrlGenerator extends \Illuminate\Routing\UrlGenerator
{
    public function to($path, $extra = [], $secure = null)
    {
        if (!in_array(config('app.env'), ['local', 'testing'])) {
            $secure = true;
        }
        $path = trim($path, '/');
        $prefix = trim(config('app.url_prefix') ?? '', '/');
        return parent::to($prefix.'/'.$path, $extra, $secure); // TODO: Change the autogenerated stub
    }
}
